name: cdstoolbox-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.7
  - black
  - cfunits
  - check-manifest
  - colorama
  - netcdf4
  - notebook
  - structlog
  - pytest
  - pytest-cov
  - pytest-flakes
  - xarray
