channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2020.10.14
  - certifi=2020.6.20
  - cffi=1.14.0
  - cftime=1.2.1
  - cfunits=3.3.0
  - chardet=3.0.4
  - conda=4.8.3
  - conda-package-handling=1.6.1
  - cryptography=2.9.2
  - curl=7.69.1
  - expat=2.2.10
  - hdf4=4.2.13
  - hdf5=1.10.4
  - idna=2.9
  - intel-openmp=2020.2
  - jpeg=9b
  - krb5=1.17.1
  - ld_impl_linux-64=2.33.1
  - libcurl=7.69.1
  - libedit=3.1.20181209
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libnetcdf=4.7.3
  - libssh2=1.9.0
  - libstdcxx-ng=9.1.0
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - ncurses=6.2
  - netcdf4=1.5.3
  - numpy=1.19.2
  - numpy-base=1.19.2
  - openssl=1.1.1h
  - pandas=1.1.3
  - pip=20.0.2
  - pycosat=0.6.3
  - pycparser=2.20
  - pyopenssl=19.1.0
  - pysocks=1.7.1
  - python=3.8.3
  - python-dateutil=2.8.1
  - pytz=2020.1
  - readline=8.0
  - requests=2.23.0
  - ruamel_yaml=0.15.87
  - setuptools=46.4.0
  - six=1.14.0
  - sqlite=3.31.1
  - structlog=20.1.0
  - tk=8.6.8
  - tqdm=4.46.0
  - udunits2=2.2.25
  - urllib3=1.25.8
  - wheel=0.34.2
  - xarray=0.16.1
  - xz=5.2.5
  - yaml=0.1.7
  - zlib=1.2.11
