name: weekly

on:
  push:
  schedule:
    - cron:  '0 9 * * 1'

jobs:
  environment:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      max-parallel: 5
      matrix:
        os: [ubuntu]
        python: [3.6, 3.7, 3.8, 3.9]
        include:
          - os: macos
            python: 3.8

    steps:
    - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python }}
          activate-environment: ${{ matrix.os }}-${{ matrix.python }}
    - name: Install dependencies and package
      shell: bash -l {0}
      run: |
        conda env update -n ${{ matrix.os }}-${{ matrix.python }} -f environment.in.yml
        conda env export -n ${{ matrix.os }}-${{ matrix.python }} --no-build | grep -v "prefix: " > environment-${{ matrix.os }}-${{ matrix.python }}.yml
    - name: Archive environment-${{ matrix.os }}-${{ matrix.python }}.yml
      uses: actions/upload-artifact@v2
      with:
        name: environment-${{ matrix.os }}-${{ matrix.python }}.yml
        path: environment-${{ matrix.os }}-${{ matrix.python }}.yml
