name: weekly

on:
  schedule:
    - cron:  '0 9 * * 1'

jobs:
  environment:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      max-parallel: 5
      matrix:
        os: [ubuntu]
        python: [3.6, 3.7, 3.8, 3.9]
        include:
          - os: macos
            python: 3.8
          - os: windows
            python: 3.7

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python }}
        activate-environment: ${{ matrix.os }}-${{ matrix.python }}
        environment-file: environment.in.yml
    - name: Export concrete dependencies
      shell: bash -l {0}
      run: |
        conda env export --no-build -f environment-${{ matrix.os }}-${{ matrix.python }}.yml
    - name: Archive environment-${{ matrix.os }}-${{ matrix.python }}.yml
      uses: actions/upload-artifact@v2
      with:
        name: environment-${{ matrix.os }}-${{ matrix.python }}.yml
        path: environment-${{ matrix.os }}-${{ matrix.python }}.yml
