name: weekly

on:
  push:
  schedule:
    - cron:  '0 9 * * 1'

jobs:
  environment:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      max-parallel: 5
      matrix:
        os: [ubuntu]
        python: [3.6, 3.7, 3.8, 3.9]
        include:
          - os: macos
            python: 3.8

    steps:
    - uses: actions/checkout@v2
    - name: Create conda envirnoment ${{ matrix.os }}-${{ matrix.python }}
      run: |
        # work around a permission bug in macos-latest conda setup
        [ '${{ matrix.os }}' == macos ] && sudo chown -R 501:20 /usr/local/miniconda
        $CONDA/bin/conda init bash
        $CONDA/bin/conda create -n ${{ matrix.os }}-${{ matrix.python }} python=${{ matrix.python }}
    - name: Install dependencies and package
      shell: bash -l {0}
      run: |
        $CONDA/bin/conda activate ${{ matrix.os }}-${{ matrix.python }}
        conda env update -n ${{ matrix.os }}-${{ matrix.python }} -f environment.in.yml
        conda env export -n ${{ matrix.os }}-${{ matrix.python }} --no-build | grep -v "prefix: " > environment-${{ matrix.os }}-${{ matrix.python }}.yml
    - name: Archive environment-${{ matrix.os }}-${{ matrix.python }}.yml
      uses: actions/upload-artifact@v2
      with:
        name: environment-${{ matrix.os }}-${{ matrix.python }}.yml
        path: environment-${{ matrix.os }}-${{ matrix.python }}.yml
