name: on-push

on: [push]

jobs:
  unit-tests-posix:
    runs-on: ${{ matrix.os-version }}-latest
    strategy:
      max-parallel: 5
      matrix:
        os-version: [ubuntu]
        python-version: [3.6, 3.7, 3.8]
        include:
          - os-version: macos
            python-version: 3.8

    steps:
    - uses: actions/checkout@v2
    - name: Setup environment ${{ matrix.os-version }}-${{ matrix.python-version }}
      run: |
        # work around a permission bug in macos-latest conda setup
        [ '${{ matrix.os-version }}' == macos ] && sudo chown -R 501:20 /usr/local/miniconda
        $CONDA/bin/conda env update -n base -f tests/environment-${{ matrix.os-version }}-${{ matrix.python-version }}.yml
        $CONDA/bin/python --version
        $CONDA/bin/python -m pip install -e .
    - name: Test with pytest
      run: |
        $CONDA/bin/conda install pytest
        $CONDA/bin/pytest -v --doctest-glob="*.rst" .

  code-analysis:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Lint with flake8
      run: |
        $CONDA/bin/conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        $CONDA/bin/flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        $CONDA/bin/flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  code-style:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Check code style with black
      run: |
        $CONDA/bin/conda install black
        $CONDA/bin/black --check .
    - name: Check code style with isort
      run: |
        $CONDA/bin/conda install isort
        $CONDA/bin/isort --check .
